'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';

function CalculateHouse() {
  const router = useRouter();

  // states
  const [people, setPeople] = useState('');
  const [energyUsage, setEnergyUsage] = useState('');
  const [transportation, setTransportation] = useState('');
  const [wasteGeneration, setWasteGeneration] = useState('');
  const [foodConsumption, setFoodConsumption] = useState('');
  const [waterUsage, setWaterUsage] = useState('');
  const [carbonFootprintCalculated, setCarbonFootprintCalculated] = useState(null);

  const [toucanTokenPrice, setToucanTokenPrice] = useState(0);
  const [requiredToucanTokensCalculated, setRequiredToucanTokens] = useState(0);
  const [costCalculated, setCost] = useState(0);

  const calculateCarbonFootprint = useCallback(() => {
    const energyEmissionFactor = 0.0007867; // kg CO2e per kWh
    const transportationEmissionFactor = 2.31; // kg CO2e per liter for gasoline vehicles
    const wasteEmissionFactor = 1.2; // kg CO2e per kg
    const foodConsumptionEmissionFactor = 12.5; // kg CO2e per kg
    const waterUsageEmissionFactor = 0.5; // kg CO2e per liter

    const totalEmissions =
      parseFloat(energyUsage || '0') * energyEmissionFactor +
      parseFloat(transportation || '0') * transportationEmissionFactor +
      parseFloat(wasteGeneration || '0') * wasteEmissionFactor +
      parseFloat(foodConsumption || '0') * foodConsumptionEmissionFactor +
      parseFloat(waterUsage || '0') * waterUsageEmissionFactor;

    setCarbonFootprintCalculated(totalEmissions);
    return totalEmissions;
  }, [energyUsage, transportation, wasteGeneration, foodConsumption, waterUsage]);

  async function fetchToucanTokenPrice() {
    const response = await fetch(
      'https://api.coingecko.com/api/v3/simple/price?ids=toucan-protocol-base-carbon-tonne&vs_currencies=inr'
    );
    const data = await response.json();
    return data['toucan-protocol-base-carbon-tonne'].inr;
  }

  useEffect(() => {
    fetchToucanTokenPrice().then((price) => setToucanTokenPrice(price));
  }, []);

  useEffect(() => {
    if (carbonFootprintCalculated !== null) {
      const requiredTokens = carbonFootprintCalculated / 1000; // 1 token = 1 tCO2e
      setRequiredToucanTokens(requiredTokens);
      setCost(requiredTokens * toucanTokenPrice);
    }
  }, [carbonFootprintCalculated, toucanTokenPrice]);

  const handleSubmit = (event) => {
    event.preventDefault();
    const footprint = calculateCarbonFootprint();
    const requiredTokens = footprint / 1000;
    const totalCost = requiredTokens * toucanTokenPrice;

    router.push(`/house-result?carbonFootprint=${footprint}&tokens=${requiredTokens}&cost=${totalCost}`);
  };

  return (
    <main>
      <div className="bg-[url('/individual_impact.jpg')] bg-center bg-no-repeat bg-cover text-white h-40 p-3">
        <h2 className="mb-7 capitalize">Carbon Footprint Calculator</h2>
        <p className="text-[50px] leading-[0.87] text-center uppercase">Household Impact</p>
      </div>

      <div className="text-center m-6 mt-24 text-4xl font-semibold font-sans">For a month:</div>

      <div className="relative flex items-top justify-center min-h-[500px] bg-white sm:items-center sm:pt-0">
        <form onSubmit={handleSubmit} autoComplete="off" className="p-6 flex flex-col justify-center">
          {/* Household size */}
          <InputField
            label="Total number of people in your household:"
            id="people"
            value={people}
            setValue={setPeople}
          />

          {/* Energy usage */}
          <InputField
            label="Total energy usage by your household (in kWh):"
            id="energy"
            value={energyUsage}
            setValue={setEnergyUsage}
          />

          {/* Transportation */}
          <InputField
            label="Fuel consumption for transportation (in liters):"
            id="transportation"
            value={transportation}
            setValue={setTransportation}
          />

          {/* Waste Generation */}
          <InputField
            label="Total waste generated by your household (in kg):"
            id="waste"
            value={wasteGeneration}
            setValue={setWasteGeneration}
          />

          {/* Food Consumption */}
          <InputField
            label="Total food consumption by your household (in kg):"
            id="food"
            value={foodConsumption}
            setValue={setFoodConsumption}
          />

          {/* Water Usage */}
          <InputField
            label="Total water usage by your household (in liters):"
            id="water"
            value={waterUsage}
            setValue={setWaterUsage}
          />

          <button
            type="submit"
            className="md:w-32 bg-green-700 hover:bg-blue-dark text-white font-bold py-3 px-6 rounded-lg mt-8 ml-[450px] hover:bg-green-600 transition ease-in-out duration-300"
          >
            Calculate
          </button>
        </form>
      </div>
    </main>
  );
}

function InputField({ label, id, value, setValue }) {
  return (
    <div className="flex flex-row mb-4">
      <label
        htmlFor={id}
        className="text-2xl font-semibold text-[#5c5c61] mt-3 mx-8"
      >
        {label}
      </label>
      <input
        type="number"
        name={id}
        id={id}
        value={value}
        onChange={(event) => setValue(event.target.value)}
        className="w-[400px] py-3 px-3 rounded-lg bg-white border border-gray-400 text-gray-800 font-semibold focus:border-green-500 focus:outline-none"
      />
    </div>
  );
}

export default CalculateHouse;
